apps:
  - script: ./pi/listen_meters.py
    name: listen
    args: "14 15"
    interpreter: "/usr/bin/python3"
  - script: ./api/index.js
    name: api
  - script: ./node_modules/.bin/serve
    args: "-s -l 5000 dist"
    name: ui